changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Fixes"
      labels:
        - bug
        - fix
    - title: "♿ Accessibility"
      labels:
        - accessibility
    - title: "🔒 Security"
      labels:
        - security
    - title: "⚡ Performance"
      labels:
        - performance
    - title: "📚 Documentation"
      labels:
        - documentation
    - title: "🧰 Maintenance"
      labels:
        - dependencies
        - maintenance
        - build
        - ci
    - title: "Other Changes"
      labels:
        - "*"
