package com.sanskar.sudokunova.shared

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.sanskar.sudokunova.engine.Difficulty
import com.sanskar.sudokunova.engine.GeneratedPuzzle
import com.sanskar.sudokunova.engine.HintEngine
import com.sanskar.sudokunova.engine.SudokuBoard
import com.sanskar.sudokunova.engine.SudokuGenerator

private data class GameSnapshot(
    val board: SudokuBoard,
    val notes: Map<Int, Set<Int>>,
)

class SharedGameState(
    private val generator: SudokuGenerator = SudokuGenerator(),
    private val hintEngine: HintEngine = HintEngine(),
) {
    private var difficultyState by mutableStateOf(Difficulty.MEDIUM)

    val difficulty: Difficulty
        get() = difficultyState

    var generated by mutableStateOf(generate(Difficulty.MEDIUM))
        private set

    var board by mutableStateOf(generated.puzzle)
        private set

    var selectedIndex by mutableStateOf<Int?>(null)
        private set

    var notesMode by mutableStateOf(false)
        private set

    var notes by mutableStateOf<Map<Int, Set<Int>>>(emptyMap())
        private set

    var statusMessage by mutableStateOf("Select a cell and enter a number.")
        private set

    private var history: List<GameSnapshot> = emptyList()

    val isComplete: Boolean
        get() = board == generated.solution

    fun select(index: Int) {
        require(index in 0 until SudokuBoard.CELL_COUNT)
        selectedIndex = index
        statusMessage = if (isFixed(index)) {
            "Clue cell selected. Choose an empty cell to edit."
        } else {
            "Row ${index / 9 + 1}, column ${index % 9 + 1} selected."
        }
    }

    fun setDifficulty(value: Difficulty) {
        if (difficulty == value) return
        newGame(value)
    }

    fun newGame(value: Difficulty = difficulty) {
        difficultyState = value
        generated = generate(value)
        board = generated.puzzle
        selectedIndex = null
        notes = emptyMap()
        notesMode = false
        history = emptyList()
        statusMessage = "New ${value.displayName} puzzle ready."
    }

    fun toggleNotesMode() {
        notesMode = !notesMode
        statusMessage = if (notesMode) "Notes mode enabled." else "Notes mode disabled."
    }

    fun enter(value: Int) {
        require(value in 1..9)
        val index = selectedIndex ?: run {
            statusMessage = "Select an editable cell first."
            return
        }
        if (isFixed(index)) {
            statusMessage = "That cell is a fixed clue."
            return
        }

        pushHistory()
        if (notesMode) {
            val current = notes[index].orEmpty()
            val updated = if (value in current) current - value else current + value
            notes = if (updated.isEmpty()) notes - index else notes + (index to updated)
            statusMessage = "Candidate notes updated."
            return
        }

        board = board.withValue(index, value)
        notes = notes - index
        removePeerNote(index, value)
        statusMessage = when {
            board == generated.solution -> "Puzzle solved!"
            board.hasConflict(index) -> "That creates a conflict."
            value != generated.solution.valueAt(index) -> "That number is not correct yet."
            else -> "Good move."
        }
    }

    fun erase() {
        val index = selectedIndex ?: return
        if (isFixed(index)) return
        if (board.valueAt(index) == SudokuBoard.EMPTY && notes[index].isNullOrEmpty()) return
        pushHistory()
        board = board.withValue(index, SudokuBoard.EMPTY)
        notes = notes - index
        statusMessage = "Cell cleared."
    }

    fun undo() {
        val snapshot = history.lastOrNull() ?: run {
            statusMessage = "Nothing to undo."
            return
        }
        history = history.dropLast(1)
        board = snapshot.board
        notes = snapshot.notes
        statusMessage = "Last move undone."
    }

    fun hint() {
        val hint = hintEngine.nextHint(board) ?: run {
            statusMessage = if (isComplete) "Puzzle already solved." else "No safe hint is available."
            return
        }
        val index = hint.cellIndex
        if (isFixed(index)) return
        pushHistory()
        selectedIndex = index
        board = board.withValue(index, hint.value)
        notes = notes - index
        removePeerNote(index, hint.value)
        statusMessage = "Hint: ${hint.technique.name.replace('_', ' ').lowercase().replaceFirstChar { it.uppercase() }}."
    }

    fun reset() {
        if (board == generated.puzzle && notes.isEmpty()) return
        pushHistory()
        board = generated.puzzle
        notes = emptyMap()
        selectedIndex = null
        statusMessage = "Puzzle reset to its starting clues."
    }

    fun isFixed(index: Int): Boolean = generated.puzzle.valueAt(index) != SudokuBoard.EMPTY

    private fun pushHistory() {
        history = (history + GameSnapshot(board, notes)).takeLast(MAX_UNDO_STEPS)
    }

    private fun removePeerNote(index: Int, value: Int) {
        val row = index / SudokuBoard.SIZE
        val column = index % SudokuBoard.SIZE
        val boxRow = row / SudokuBoard.BOX_SIZE
        val boxColumn = column / SudokuBoard.BOX_SIZE
        notes = notes.mapValues { (otherIndex, values) ->
            val otherRow = otherIndex / SudokuBoard.SIZE
            val otherColumn = otherIndex % SudokuBoard.SIZE
            val isPeer = otherRow == row ||
                otherColumn == column ||
                (otherRow / SudokuBoard.BOX_SIZE == boxRow && otherColumn / SudokuBoard.BOX_SIZE == boxColumn)
            if (isPeer) values - value else values
        }.filterValues { it.isNotEmpty() }
    }

    private fun generate(value: Difficulty): GeneratedPuzzle = generator.generate(value)

    private companion object {
        const val MAX_UNDO_STEPS = 100
    }
}
