package com.sanskar.sudokunova.shared

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.sanskar.sudokunova.engine.Difficulty
import com.sanskar.sudokunova.engine.GeneratedPuzzle
import com.sanskar.sudokunova.engine.HintEngine
import com.sanskar.sudokunova.engine.PuzzleExchangeService
import com.sanskar.sudokunova.engine.SudokuBoard
import com.sanskar.sudokunova.engine.SudokuGenerator

private data class GameSnapshot(
    val board: SudokuBoard,
    val notes: Map<Int, Set<Int>>,
)

class SharedGameState(
    private val generator: SudokuGenerator = SudokuGenerator(),
    private val hintEngine: HintEngine = HintEngine(),
    private val puzzleExchangeService: PuzzleExchangeService = PuzzleExchangeService(),
) {
    private var difficultyState by mutableStateOf(Difficulty.MEDIUM)

    val difficulty: Difficulty
        get() = difficultyState

    var generated by mutableStateOf(generate(Difficulty.MEDIUM))
        private set

    var board by mutableStateOf(generated.puzzle)
        private set

    var selectedIndex by mutableStateOf<Int?>(null)
        private set

    var notesMode by mutableStateOf(false)
        private set

    var notes by mutableStateOf<Map<Int, Set<Int>>>(emptyMap())
        private set

    var status by mutableStateOf<SharedGameStatus>(SharedGameStatus.SelectCell)
        private set

    private var history: List<GameSnapshot> = emptyList()

    var sourceCode by mutableStateOf<String?>(null)
        private set

    val isImported: Boolean
        get() = sourceCode != null

    val isComplete: Boolean
        get() = board == generated.solution

    fun select(index: Int) {
        require(index in 0 until SudokuBoard.CELL_COUNT)
        selectedIndex = index
        status = statusForSelection(index)
    }

    fun moveSelection(rowDelta: Int, columnDelta: Int) {
        require(rowDelta in -1..1 && columnDelta in -1..1) {
            "Selection movement must stay within one row and one column per step."
        }
        require(rowDelta != 0 || columnDelta != 0) {
            "Selection movement requires a non-zero row or column delta."
        }

        val current = selectedIndex
        if (current == null) {
            select(0)
            return
        }

        val row = (current / SudokuBoard.SIZE + rowDelta).coerceIn(0, SudokuBoard.SIZE - 1)
        val column = (current % SudokuBoard.SIZE + columnDelta).coerceIn(0, SudokuBoard.SIZE - 1)
        select(row * SudokuBoard.SIZE + column)
    }

    fun setDifficulty(value: Difficulty) {
        if (difficulty == value) return
        newGame(value)
    }

    fun newGame(value: Difficulty = difficulty) {
        difficultyState = value
        generated = generate(value)
        board = generated.puzzle
        selectedIndex = null
        notes = emptyMap()
        notesMode = false
        sourceCode = null
        history = emptyList()
        status = SharedGameStatus.NewPuzzle(value)
    }

    /**
     * Imports a puzzle only after [PuzzleExchangeService] has verified that the
     * SNP1 payload decodes and has exactly one solution. The canonical code is
     * retained so active-session restore can reconstruct the same puzzle rather
     * than generating a replacement from a seed.
     */
    fun importPuzzleCode(raw: String): Boolean {
        val imported = puzzleExchangeService.importCode(raw.trim()) ?: run {
            status = SharedGameStatus.InvalidPuzzleCode
            return false
        }
        val canonicalCode = puzzleExchangeService.exportCode(imported.puzzle, imported.difficulty)
        difficultyState = imported.difficulty
        generated = GeneratedPuzzle(
            puzzle = imported.puzzle,
            solution = imported.solution,
            difficulty = imported.difficulty,
            assessment = imported.assessment,
            seed = 0L,
        )
        board = imported.puzzle
        selectedIndex = null
        notes = emptyMap()
        notesMode = false
        sourceCode = canonicalCode
        history = emptyList()
        status = SharedGameStatus.ImportedPuzzle(imported.difficulty)
        return true
    }

    fun puzzleCode(): String =
        puzzleExchangeService.exportCode(generated.puzzle, difficulty)

    fun snapshot(): SharedGameSnapshot = SharedGameSnapshot(
        difficulty = difficulty,
        seed = generated.seed,
        board = board.toPuzzleString(),
        notes = notes.mapValues { (_, values) -> values.toSet() },
        selectedIndex = selectedIndex,
        notesMode = notesMode,
        sourceCode = sourceCode,
    )

    fun restore(snapshot: SharedGameSnapshot): Boolean {
        val restored = runCatching {
            val imported = snapshot.sourceCode?.let { puzzleExchangeService.importCode(it) }
            if (snapshot.sourceCode != null) {
                requireNotNull(imported) { "Stored source puzzle code is invalid." }
                require(imported.difficulty == snapshot.difficulty) {
                    "Stored source puzzle difficulty does not match the snapshot."
                }
            }
            val regenerated = imported?.let {
                GeneratedPuzzle(
                    puzzle = it.puzzle,
                    solution = it.solution,
                    difficulty = it.difficulty,
                    assessment = it.assessment,
                    seed = 0L,
                )
            } ?: generate(snapshot.difficulty, snapshot.seed)
            val startingBoard = regenerated.puzzle
            val restoredBoard = SudokuBoard.parse(snapshot.board)
            requireMatchesStartingClues(startingBoard, restoredBoard)
            requireValidNotes(startingBoard, restoredBoard, snapshot.notes)
            require(snapshot.selectedIndex == null || snapshot.selectedIndex in 0 until SudokuBoard.CELL_COUNT) {
                "Selected cell index is outside the Sudoku board."
            }
            RestoredGame(
                generated = regenerated,
                board = restoredBoard,
                notes = snapshot.notes.mapValues { (_, values) -> values.toSet() },
                sourceCode = snapshot.sourceCode,
            )
        }.getOrNull() ?: return false

        difficultyState = snapshot.difficulty
        generated = restored.generated
        board = restored.board
        notes = restored.notes
        selectedIndex = snapshot.selectedIndex
        notesMode = snapshot.notesMode
        sourceCode = restored.sourceCode
        history = emptyList()
        status = selectedIndex?.let(::statusForSelection) ?: SharedGameStatus.SelectCell
        return true
    }

    fun toggleNotesMode() {
        notesMode = !notesMode
        status = if (notesMode) SharedGameStatus.NotesEnabled else SharedGameStatus.NotesDisabled
    }

    fun enter(value: Int) {
        require(value in 1..9)
        val index = selectedIndex ?: run {
            status = SharedGameStatus.SelectEditableCell
            return
        }
        if (isFixed(index)) {
            status = SharedGameStatus.FixedClue
            return
        }

        pushHistory()
        if (notesMode) {
            val current = notes[index].orEmpty()
            val updated = if (value in current) current - value else current + value
            notes = if (updated.isEmpty()) notes - index else notes + (index to updated)
            status = SharedGameStatus.NotesUpdated
            return
        }

        board = board.withValue(index, value)
        notes = notes - index
        removePeerNote(index, value)
        status = when {
            board == generated.solution -> SharedGameStatus.Solved
            board.hasConflict(index) -> SharedGameStatus.Conflict
            value != generated.solution.valueAt(index) -> SharedGameStatus.Incorrect
            else -> SharedGameStatus.GoodMove
        }
    }

    fun erase() {
        val index = selectedIndex ?: return
        if (isFixed(index)) return
        if (board.valueAt(index) == SudokuBoard.EMPTY && notes[index].isNullOrEmpty()) return
        pushHistory()
        board = board.withValue(index, SudokuBoard.EMPTY)
        notes = notes - index
        status = SharedGameStatus.CellCleared
    }

    fun undo() {
        val snapshot = history.lastOrNull() ?: run {
            status = SharedGameStatus.NothingToUndo
            return
        }
        history = history.dropLast(1)
        board = snapshot.board
        notes = snapshot.notes
        status = SharedGameStatus.MoveUndone
    }

    fun hint() {
        val hint = hintEngine.nextHint(board) ?: run {
            status = if (isComplete) SharedGameStatus.AlreadySolved else SharedGameStatus.NoSafeHint
            return
        }
        val index = hint.cellIndex
        if (isFixed(index)) return
        pushHistory()
        selectedIndex = index
        board = board.withValue(index, hint.value)
        notes = notes - index
        removePeerNote(index, hint.value)
        status = SharedGameStatus.Hint(hint.technique)
    }

    fun reset() {
        if (board == generated.puzzle && notes.isEmpty()) return
        pushHistory()
        board = generated.puzzle
        notes = emptyMap()
        selectedIndex = null
        status = SharedGameStatus.Reset
    }

    fun isFixed(index: Int): Boolean = generated.puzzle.valueAt(index) != SudokuBoard.EMPTY

    private fun statusForSelection(index: Int): SharedGameStatus = if (isFixed(index)) {
        SharedGameStatus.FixedCellSelected
    } else {
        SharedGameStatus.CellSelected(
            row = index / SudokuBoard.SIZE + 1,
            column = index % SudokuBoard.SIZE + 1,
        )
    }

    private fun requireMatchesStartingClues(startingBoard: SudokuBoard, restoredBoard: SudokuBoard) {
        for (index in 0 until SudokuBoard.CELL_COUNT) {
            val clue = startingBoard.valueAt(index)
            require(clue == SudokuBoard.EMPTY || restoredBoard.valueAt(index) == clue) {
                "Restored board changes a fixed starting clue at index $index."
            }
        }
    }

    private fun requireValidNotes(
        startingBoard: SudokuBoard,
        restoredBoard: SudokuBoard,
        restoredNotes: Map<Int, Set<Int>>,
    ) {
        for ((index, values) in restoredNotes) {
            require(index in 0 until SudokuBoard.CELL_COUNT) { "Note cell index is outside the Sudoku board." }
            require(startingBoard.valueAt(index) == SudokuBoard.EMPTY) { "Notes cannot target a fixed clue." }
            require(restoredBoard.valueAt(index) == SudokuBoard.EMPTY) { "Notes cannot target a filled cell." }
            require(values.isNotEmpty() && values.all { it in 1..9 }) { "Note values must be non-empty digits 1..9." }
        }
    }

    private fun pushHistory() {
        history = (history + GameSnapshot(board, notes)).takeLast(MAX_UNDO_STEPS)
    }

    private fun removePeerNote(index: Int, value: Int) {
        val row = index / SudokuBoard.SIZE
        val column = index % SudokuBoard.SIZE
        val boxRow = row / SudokuBoard.BOX_SIZE
        val boxColumn = column / SudokuBoard.BOX_SIZE
        notes = notes.mapValues { (otherIndex, values) ->
            val otherRow = otherIndex / SudokuBoard.SIZE
            val otherColumn = otherIndex % SudokuBoard.SIZE
            val isPeer = otherRow == row ||
                otherColumn == column ||
                (otherRow / SudokuBoard.BOX_SIZE == boxRow && otherColumn / SudokuBoard.BOX_SIZE == boxColumn)
            if (isPeer) values - value else values
        }.filterValues { it.isNotEmpty() }
    }

    private fun generate(value: Difficulty): GeneratedPuzzle = generator.generate(value)

    private fun generate(value: Difficulty, seed: Long): GeneratedPuzzle = generator.generate(value, seed)

    private data class RestoredGame(
        val generated: GeneratedPuzzle,
        val board: SudokuBoard,
        val notes: Map<Int, Set<Int>>,
        val sourceCode: String?,
    )

    private companion object {
        const val MAX_UNDO_STEPS = 100
    }
}
